### PR TITLE
Full native Linux compatibility

### PR DESCRIPTION
**Pull request by zachrammell**
everything now works as it does on Windows

### CODE REVIEW

**Review by BrayanLopezDev — APPROVED** [review]
I'll have to look closely at your serialization changes because I'm also making some minor changes there... but I'll approve it

**Comment by HardGaming01** [comment]
At line 136 of TraceLogger.cpp
 https://github.com/digipen-team-uwu/uwu-engine/blob/ea5c008bf6bcbfc65d3bb3daeb8747ed89b01046/src/Debugs/TraceLogger.cpp#L136
MSVC doesn't support outputting a wstring to standard cout. it is required to use a wide version wcout. Please test if this is supported in linux.

Also at line 294,
https://github.com/digipen-team-uwu/uwu-engine/blob/ea5c008bf6bcbfc65d3bb3daeb8747ed89b01046/src/Debugs/TraceLogger.cpp#L294
it warns about outputting a unicode character into cout being a deleted function in MSVC. Although the program still compiled successfully this seems pretty severe.
image

**Review by HardGaming01 — APPROVED** [review]
Everything works

**Comment by zachrammell** [comment]
I removed the following snippet:
https://github.com/digipen-team-uwu/uwu-engine/blob/ea5c008bf6bcbfc65d3bb3daeb8747ed89b01046/src/Debugs/TraceLogger.cpp#L136

**Pull request merged**
