### PR TITLE
Drag n Drop now works for JSONS

### PR DESCRIPTION
**Pull request by BrayanLopezDev**
Had to change EntityFactory to work with being given a filename as well as a type to create an entity. Currently crashes when given a Spine JSON.

### CODE REVIEW

**Review by zachrammell — APPROVED** [review]
Works very well.

**Comment by zachrammell** [comment]
note: can't really be tested at the moment because of the rebase (timers are broken)
if you want to review this just look at the code

**Comment by zachrammell** [comment]
Can somebody else please review this?

**Review by HardGaming01 — APPROVED** [review]
Great Job!!!!!!!! 
also this issue is fixed now. #32

**Pull request merged**
