### PR TITLE
refactored hierarchy to decrease cpu usage

### PR DESCRIPTION
**Pull request by hadialhussieni**

### CODE REVIEW

**Review by chaun-nguyen — APPROVED** [review]
good job Hadi

**Review by chaun-nguyen — APPROVED** [review]
good job Hadi!

Edit by hadi: thanks chau!!!

**Comment by hadialhussieni** [comment]
thanks for the reviews guys!

**Review by zachrammell — APPROVED** [review]
Looks good, tested on linux

**Pull request merged**
